### ISSUE TITLE
Error downloading feed (Invalid SSL Certificate)

### ISSUE THREAD

**Issue by megadr01d** [pictuga/morss#13]
This feed used to work until a couple of days ago when it started returning the error "Error downloading feed (Invalid SSL Certificate)". Without parsing it through morss, the feed loads fine in Firefox.
I guess this is not related to morss but is this certificate check mandatory?

http://morss.it/https://authoritynutrition.com/feed

Thanks for the great project.

**Comment by pictuga** [comment]
The issue seems to work with the [test](http://test.morss.it/) version of morss
http://test.morss.it/https://authoritynutrition.com/feed
Probably due to the fact that the main http://morss.it/ always uses aged versions of the script (still have to implement proper unit testing before going rolling release)

**Comment by megadr01d** [comment]
When I reported it, it also failed using the test version. Then the default version complained about disk quota exceeded. A month ago or so, it started working fine again.
