### ISSUE TITLE
Web doesn't work

### ISSUE THREAD

**Issue by ghost** [pictuga/morss#21]
First I received a 50x error. Now landing page is displayed but it can't connect to any feed. Are you working to have morss.it up & ready again?

**Comment by pictuga** [comment]
Seems like my hosting provider suddenly decided to withdraw its support of a python library (lxml), needed to make morss work. Might have to shift to another server. Working on that, but kinda short on time these days. Will try to fix it ASAP

**Comment by ilya-bystrov** [comment]
It would be great to fix it.

**Comment by pictuga** [comment]
Back online

**Comment by megadr01d** [comment]
But not working

```
http://morss.it/www.healthy-holistic-living.com/feed

An error happened:
database is locked
```

**Comment by pictuga** [comment]
Fixed, now using mysql as a cache backend instead of sqlite
Probably gonna run into "database full" issues sson
The volume is higher than I anticipated when I started the project...

**Comment by q1316480** [comment]
The problem is that you are (or you was?) "the last" full RSS service.

I was using other, but they close. Every time that a service close I search another, and last time I found morss (I supose that other people too).

I triyed to install morss in my Raspberry Pi. It worked (I go with my browser and I get the full RSS feed), but it doesn't work with Feedly (I supose that is very slow to answer?)

**Comment by pictuga** [comment]
Reopening the bug as the website is down again -- database got full in less than 24h, the service is definitely more popular than anticipated

**Comment by pictuga** [comment]
Back online. Will push the commits soon (basically limits the size of the mysql ache)
