### ISSUE TITLE
Feed is dropping items that are not the same domain

### ISSUE THREAD

**Issue by skoshy** [pictuga/morss#35]
I'm trying to use morss with Lifehacker (https://lifehacker.com/rss), and it works great in combined mode, except all items from domains other than `lifehacker.com` are stripped out from the feed.

For instance, items with a link to `https://lifehacker.com` and `https://vitals.lifehacker.com` are kept, but items linking to `https://kinjadeals.theinventory.com` or `https://theinventory.com` are dropped.

Any ideas on how to avoid this?

**Comment by pictuga** [comment]
I can't replicate the bug right now. Could you share a screenshot maybe?

Could this be due to the fact that morss automatically drops "old" items from the feed?

**Comment by skoshy** [comment]
So for example, when looking at the Lifehacker RSS feed above, you can see there's an item for a Kinja Deals link:

https://lifehacker.com/rss
![image](https://user-images.githubusercontent.com/369825/86612423-19ed7b80-bf7e-11ea-9a96-c96bbe6650c1.png)

But when viewing through Morss, it skips that and just shows the quarters article as the first article instead

https://morss.it/:clip/https://lifehacker.com/rss
![image](https://user-images.githubusercontent.com/369825/86612467-2b368800-bf7e-11ea-9fb9-a1a5005b4ece.png)

**Comment by pictuga** [comment]
Indeed... Does it work better with this feed https://morss.it/:first/https:/lifehacker.com/rss ? (making use of the newly introduced `:first` toggle)

The "GameCube" article was getting dropped due to sorting (morss picks article by _time_ not by sequence in the feed) and lifehacker seems to put articles in semi random order (the next "Coin Shortage" article is nearly 2 hours _newer_ than the previous one)

**Comment by skoshy** [comment]
Yes it looks like the Kinja Deals items are coming through with that toggle!

Strangely though, now when I disable that toggle, I'm still seeing the Kinja Deals gamecube article https://morss.it/https:/lifehacker.com/rss

![image](https://user-images.githubusercontent.com/369825/86619642-00056600-bf89-11ea-888c-eb1542235409.png)
![image](https://user-images.githubusercontent.com/369825/86619665-072c7400-bf89-11ea-9b01-4fb38fdbc0f8.png)


It looks like it now works without needing that toggle?

**Comment by pictuga** [comment]
Since the Kinja Deals has been cached when viewing it with `:first`, it now appears also in the standard view, but this is only due to the timing of the caching (cache gets cleared aggressively, so don't rely on it). So I'd suggest you keep the toggle on for the time being ;)

(That being said, I'll probably switch the default behaviour with that of `:first`, as it probably confuses people)

**Comment by pictuga** [comment]
I've changed the code just now (f18a128ee6626a4cc25c4abce01bdc6777c5d663). Default behaviour is now that of `:first` (have to use `:newest` to get back to the "old" confusing behaviour)

**Comment by pictuga** [comment]
Problem seems solved. Feel free to reopen the issue of need be!
